spring:
  profiles:
    active: development
  data:
    rest:
      base-path: /api
    mongodb:
      auto-index-creation: true
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
springdoc:
  packages-to-scan: io.meraklis.icare
#  swagger-ui:
#    filter: Top Flight Scheduler
okta:
  oauth2:
    issuer: ${AUTH0_ISSUER}
    client-id: ${AUTH0_CLIENT_ID}
    client-secret: ${AUTH0_CLIENT_SECRET}
s3:
  bucket: "poneres-portal"
  region: ${AWS_REGION}
  access-key: ${AWS_ACCESS_KEY}
  access-secret: ${AWS_ACCESS_SECRET}
email:
  poneres:
    no-reply: "no-reply@poneres.com"
    to: evangelos.poneres@gmail.com,test@cool.io
  xeniteas:
    no-reply: "no-reply@pontiangreeks.org"
    to: evangelos.poneres@gmail.com,test@cool.io
auth0:
  administration:
    client-id: ${AUTH0_ADMIN_CLIENT_ID}
    client-secret: ${AUTH0_ADMIN_CLIENT_SECRET}
stripe:
  private-key: ${STRIPE_PRIVATE_KEY}
signwell:
  api-url: "https://www.signwell.com/api/v1/"
  api-key: ${SIGNWELL_API_KEY}
  test-mode: true
webapp:
  url: "https://poneres-portal-erg0gza3d2hwc6dh.eastus2-01.azurewebsites.net"
server:
  error:
    include-message: always
logging:
  level:
    org:
      apache:
        pdfbox: error
#      springframework:
#        data:
#          mongodb:
#            core:
#              MongoTemplate: DEBUG
pdf:
  fields-preview: true
management:
  endpoints:
    web:
      exposure:
        include: env
  endpoint:
    env:
      show-values: always
