spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
okta:
  oauth2:
    issuer: ${AUTH0_ISSUER}
    client-id: ${AUTH0_CLIENT_ID}
    client-secret: ${AUTH0_CLIENT_SECRET}
s3:
  region: ${AWS_REGION}
  access-key: ${AWS_ACCESS_KEY}
  access-secret: ${AWS_ACCESS_SECRET}
auth0:
  administration:
    client-id: ${AUTH0_ADMIN_CLIENT_ID}
    client-secret: ${AUTH0_ADMIN_CLIENT_SECRET}
