spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: "poneres-portal"
webapp:
  url: "https://poneres-portal-erg0gza3d2hwc6dh.eastus2-01.azurewebsites.net"
email:
  poneres:
    to: hello@poneres.com
  xeniteas:
    to: pontiangreeks@gmail.com,evangelos.poneres@gmail.com
signwell:
  test-mode: false
