spring:
  profiles:
    active: production
  data:
    rest:
      base-path: /api
    mongodb:
      database: "poneres-portal"
      auto-index-creation: true
s3:
  bucket: "poneres-portal"
server:
  error:
    include-message: always
logging:
  level:
    org:
      apache:
        pdfbox: error
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
springdoc:
  packages-to-scan: io.meraklis.icare
#  swagger-ui:
#    filter: Top Flight Scheduler
email:
  no-reply: "hello@poneres.com"
webapp:
  url: "https://poneres-portal-erg0gza3d2hwc6dh.eastus2-01.azurewebsites.net"
