spring:
  data:
    rest:
      base-path: /api
    mongodb:
      uri: ${MONGODB_URI}
      database: "poneres-portal"
okta:
  oauth2:
    issuer: ${AUTH0_ISSUER}
    client-id: ${AUTH0_CLIENT_ID}
    client-secret: ${AUTH0_CLIENT_SECRET}
s3:
  bucket: "poneres-portal"
  region: ${AWS_REGION}
  access-key: ${AWS_ACCESS_KEY}
  access-secret: ${AWS_ACCESS_SECRET}
auth0-administration:
  client-id: "bRRx6aDajaSNEmWBBeBC9u05NGdcFvHA"
  client-secret: "EAGc-ra1DL9yWi7JSSubd3yTy7fdlU1uG4_trI4bVx8xCfAML5pOcl8j9hv9hq8W"
