spring:
  profiles:
    active: production
logging:
  level:
    org:
      apache:
        pdfbox: error
#      springframework:
#        data:
#          mongodb:
#            core:
#              MongoTemplate: DEBUG
springdoc:
  packages-to-scan: io.meraklis.icare.top_flight
  swagger-ui:
    filter: Top Flight Scheduler
