spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: "poneres-portal"
webapp:
  url: "https://poneres-portal-erg0gza3d2hwc6dh.eastus2-01.azurewebsites.net"
pdf:
  fields-preview: false
email:
  applications:
    to: evangelos.poneres@gmail.com,poneres.c@gmail.com
signwell:
  test-mode: false
